#################################################################################
#
# Example Makefile
#
#################################################################################

# Useful Variables

PYTHON_INTERPRETER = python
WD=$(shell pwd)
PYTHONPATH=${WD}
SHELL := /bin/bash
PIP := pip

#
# .PHONY: all
all: 
  $(info $$WD is [${WD}])echo Hello world