#################################################################################
#
# Example Makefile
#
#################################################################################

# Variables

PYTHON_INTERPRETER=python
PIP=pip
PYTHONPATH=$(shell pwd)
SHELL=/bin/bash # If this isn't set the shell will default to `sh`


$(info PYTHONPATH: $(PYTHONPATH))

# 1: Create the virtual environment

# 2: Install project dependancies 

# 3: Run tests